[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robotni"
version = "0.1.0"
description = "A minimal, file-based task scheduler to run Python jobs from a web app, with async task queuing and status polling."
authors = [
    { name="Your Name", email="your.email@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "uvicorn",
    "huey",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx"
]
